export const inputs = {
  step1: [
    {
      label: "Milage",
      placeholder: "11111",
      cid: "milageControl",
      type: "text",
      component: "input",
    },
    {
      label: "Zip Code",
      placeholder: "11111",
      cid: "zipControl",
      type: "text",
      component: "input",
    },
    {
      label: "Exterior Color",
      placeholder: "Blue",
      cid: "exteriorColorControl",
      type: "text",
      component: "input",
    },
    {
      label: "Interior Color",
      placeholder: "Black",
      cid: "interiorColorControl",
      type: "text",
      component: "input",
    },
  ],
  step2: [
    {
      label: "Origional Owner",
      placeholder: "yes",
      cid: "ownerControl",
      type: "radio",
      component: "input",
      options: ["yes", "no"],
    },
    {
      label: "Drivetrain",
      placeholder: "N/A",
      cid: "drivetrainControl",
      type: "select",
      component: "select",
      options: ["Select drivetrain"],
    },
    {
      label: "Transmission",
      placeholder: "Automatic",
      cid: "transmissionControl",
      type: "select",
      component: "select",
      options: ["Select transmission"],
    },
    {
      label: "Engine",
      placeholder: "N/A",
      cid: "engineControl",
      type: "select",
      component: "select",
      options: ["Select engine"],
    },
  ],
  step3: [
    {
      label: "Convience Options",
      placeholder: "",
      cid: "convienceControl",
      type: "checkbox",
      component: "input",
      options: [
        "cruiser control",
        "cooled seats",
        "heated seats",
        "heated steerig wheel",
        "keyless start",
        "navigation system",
        "power liftgate",
        "remote start",
      ],
    },
    {
      label: "Entertainment Options",
      placeholder: "",
      cid: "entertainmentControl",
      type: "checkbox",
      component: "input",
      options: [
        "apple / adroid play",
        "bluetooth",
        "homelink",
        "premium sound system",
        "rear seat entertainment",
        "USB port",
      ],
    },
    {
      label: "Exterior Options",
      placeholder: "",
      cid: "exteriorControl",
      type: "checkbox",
      component: "input",
      options: ["alloy wheels", "sun/moon roof", "tow hitch", "tow hooks"],
    },
  ],
  step4: [
    {
      label: "Saftey Options",
      placeholder: "",
      cid: "safteyControl",
      type: "checkbox",
      component: "input",
      options: [
        "automatic emergency braking",
        "backup camera",
        "blind spot monitor",
        "brake assist",
        "lane departure warning",
        "LED headlights",
        "rear cross traffic alert",
        "stability control",
      ],
    },
    {
      label: "Seating Options",
      placeholder: "",
      cid: "seatingControl",
      type: "checkbox",
      component: "input",
      options: ["Leather seats", "memory seat", "third row seating"],
    },
  ],
  step5: [
    {
      label: "Listing Price",
      placeholder: "$20,000",
      cid: "listingPriceControl",
      type: "text",
      component: "input",
    },
    {
      label: "Additional Information",
      placeholder: "Add some notes about the car here",
      cid: "additionalInformationControl",
      type: "textarea",
      component: "textarea",
    },
  ],
  step6: [
    {
      label: "Upload Car Photos (optional)",
      placeholder: "",
      cid: "photoControl",
      type: "file",
      component: "input",
    },
  ],
  step7: {},
};
